DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS book;
CREATE TABLE genre(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE author(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE book(ID BIGINT PRIMARY KEY, TITLE VARCHAR(255), ID_AUTHOR BIGINT, ID_GENRE BIGINT);

